philosopy
Sage-Bionetworks/developer-handbook pull request #4
Opened 2022-03-15 21:58 UTC by tthyer

proposed philosophy -- needs criticism

depends on #3

2022-03-16 00:37 UTC, thomasyu888 commented
I like it - this is less of feedback then just a slight re-write. Let me know your thoughts.


> Coding conventions are a MUST when we want successful collaboration.  We are plural, and we want to work together on these conventions in a deliberate way.  This is an evolving document - we want to repeatedly discuss, write, and review these guidelines.

> For coders, the code is part of how we live - it’s similar to how you organize your residence. To some people, it really matters where the milk is in the refrigerator, or whether the utensils are put in the dishwasher pointy-side up or down. These are the conventions and the preferences.  But, other things are best practices -- you really SHOULD change those batteries in your fire alarm once per year. Still others are REQUIRED, like having to pay property taxes or rent every year.

> Coding conventions allow us to get our work done smoothly in an optimally social way.

> This is a handbook of both these conventions as well as practical tips on how to get things done.

2022-03-16 18:43 UTC, tthyer commented
@thomasyu888 Re-read this a few times and decided I really like your rewrite except not so much the very first line. That said, I wanted to hold off on this PR until the code space meeting on Friday to get more feedback from the group. cc @mattfazza

2022-03-22 19:45 UTC, mattfazza commented
### 1st Paragraph: small rewrite.

> _Coding conventions are pivotal in successful collaboration._ We are plural, and we want to work together on these conventions in a deliberate way.  This is meant to be an evolving document - we want to repeatedly discuss, write, and review these.

### 2nd Paragraph: if this repository is intended for an audience who codes, I don't see this entire comparison being necessary. 

> For coders, the code is part of how we live - it’s similar to how you organize your residence. To some people, it really matters where the milk is in the refrigerator, or whether the utensils are put in the dishwasher pointy-side up or down. These are the conventions and the OPTIONAL but RECOMMENDED preferences. But, other things are best practices -- you really SHOULD change those batteries in your fire alarm once per year. Then there are the REQUIRED, like having to pay property taxes or rent every year.

### 3rd Paragraph: small addition.

> Coding conventions allow us to get our work done smoothly in an optimally social way, _by adding predictability, uniformity, and proven standards to the way we write code._

### 4th Paragraph: small revision.

> This handbook documents these conventions as well as practical tips on how to get things done.

2022-03-22 19:45 UTC, mattfazza requested changes
It's in the comments.  Let's discuss

2022-03-22 23:12 UTC, tthyer commented
@thomasyu888 @mattfazza Thanks! I'm gathering together the content suggestions. As for specific word choices and phrasing, I'm going to be meeting with Zoe / other writing experts.

2022-04-08 18:51 UTC, thomasyu888 commented
Thanks Matt, Tess for drafting and reviewing.  I discussed with Zoe and this was the text we came up with.  I will make modifications to the PR soon.

> We create and maintain coding conventions to ensure successful collaboration. We want to work together on these conventions in a deliberate way, repeatedly discussing, writing, and reviewing this evolving document.

> For coders, the code is part of how we live - it’s similar to how you organize your residence. To some people, it really matters that forks face handle-up in the dishwasher, or that the toilet paper hangs over the roll. These are the conventions and the optional but recommended preferences. But, other things are best practices -- you really should change those batteries in your fire alarm once per year. Then there are the required, like having to pay utilities.

> Coding conventions add predictability, uniformity, and proven standards to the way we write code, which allows us to work more efficiently. This handbook documents these conventions and suggests practical tips.

2022-04-19 16:18 UTC, mattfazza commented on content/pages/000_meta/philosophy.md
I like the way this is written.

2022-04-19 16:19 UTC, mattfazza commented on content/pages/000_meta/philosophy.md
> +Coding conventions add predictability, uniformity, and proven standards to the way we write code, which allows us to work more efficiently. This handbook documents these conventions and suggests prac
+1 for this one. 🥇

2022-04-19 16:21 UTC, mattfazza commented on content/pages/000_meta/philosophy.md
I'm not against this part, I just don't find it necessary.

2022-04-19 16:21 UTC, mattfazza approved these changes

2022-04-28 08:11 UTC, merged